version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: solva-postgres
    environment:
      POSTGRES_DB: solva-coffee
      POSTGRES_USER: solva-admin
      POSTGRES_PASSWORD: solva-admin-123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - solva-network

volumes:
  postgres_data:

networks:
  solva-network:
    driver: bridge
